repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    # default black line length is 88
    args:
      - --target-version=py35
      - --line-length=79
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    args:
      # flake8 is not PEP8 compliant
      # https://black.readthedocs.io/en/stable/the_black_code_style.html
      - --ignore=E203,W503
    # default flake8 line length is 79
